### ISSUE TITLE
Add ability to justify individual items on main axis

### ISSUE THREAD

**Issue by simonsmith** [suitcss/utils-flex#1]
[This article](https://medium.com/@samserif/flexbox-s-best-kept-secret-bd3d892826b6#.fypa57bks) details how `margin: auto` can be used to achieve an `align-self` effect but on the main axis. Here is [an example](http://codepen.io/simonsmith/pen/VeYRPW).

I'm proposing four additional rules to allow this, but not sure on best naming. One choice might be

```css
.u-flexJustifySelfRight {
  margin-left: auto;
}
```

Issue here could be that these rules have no idea what the `flex-direction` is so they need to be called `Right` instead of `End`. If it was set to `column` then `margin-top: auto` would be needed instead via `.flexJustifySelfBottom`. Same issues with `row-reverse` etc. Also this naming implies it might work the same as `align-self` which it doesn't. 

Another idea could be `u-flexMarginAutoLeft` but that feels more confusing perhaps.

Thoughts @timkelty?

**Comment by timkelty** [comment]
@simonsmith Interesting! So we're basically addressing the fact that there is not `justify-self` property, right?

In your example, the same result can be achieved with just:

```css
.right {
  align-self: flex-end;
}
```
[Here's an an example](http://codepen.io/timkelty/pen/VeLQge/) (I think...) of something where you would need the margin auto to achieve the same thing you can with floats/overflow.

Anyway...I love it! But yes, hard to characterize in a class name.

> Also this naming implies it might work the same as align-self which it doesn't.

That's my biggest worry, not bothered as much by the top/bottom/left/right confusion, as that is someone expected with flexbox.

I might prefer something like:

```
.u-flexExpandRight {
  margin-right: auto;
}
```

That way you know the `Right` part of the class is always matching the margin direction, and it also doesn't imply its doing the same thing as `align-self`.

Another idea, would be to just be aware of this behavior, not have it be part of `utils-flex` and bring back a margin/spacing component:

```
.u-marginRightAuto {
    margin-right: auto;
}
```

**Comment by simonsmith** [comment]
I think I prefer your second option of `.u-flexExpandRight` as it gets rid of the confusion of the margin direction. Also like that it keeps it in this package and not depending on an additional util (which might require `sm`, `md` etc)

Just need some decent docs and an example to go with it

**Comment by timkelty** [comment]
Yep, I like that too.
I just used it in a project and it felt pretty intuitive.

**Comment by simonsmith** [comment]
Great, even better if it's been tested
