### ISSUE TITLE
Specificity problem 

### ISSUE THREAD

**Issue by illycz** [suitcss/utils-flex#6]
If I have flat selectors and I need override some flex declarations, there is specificity problem: https://github.com/suitcss/utils-flex/blob/master/lib/flex.css#L144-L147

Any suggestions about that?

Thanks

**Comment by giuseppeg** [comment]
@simonsmith any reason why that rule is not `!important`?

**Comment by simonsmith** [comment]
I think I assumed it was a stepping over it's boundaries by effecting all flex children. It seems that it's causing a specificity problem regardless.

Considering it's just there for IE10 maybe we can approach it another way

**Comment by simonsmith** [comment]
Perhaps one option is to provide `u-flexShrink` rules alongside the `u-flexGrow` (this would likely be useful anyway) and users can apply the shrink class manually if they need to fix IE10. We could document this one edge case in the README.

**Comment by illycz** [comment]
@giuseppeg only philosophical :)
@simonsmith maybe documented utility like .u-flexShrink1?

**Comment by simonsmith** [comment]
> maybe documented utility like .u-flexShrink1?

Some mind reading stuff right there :)

I'll look at this later today

**Comment by illycz** [comment]
@simonsmith my specialization or I am slower :)

**Comment by illycz** [comment]
@simonsmith nice!
